### ISSUE TITLE
Unable to deploy on my raspberry pi 3B+

### ISSUE THREAD

**Issue by LoSunny** [crra/focalboard-native-docker#1]
The focalboard instance crashes when it starts, here is the build & start logs: https://hastebin.com/yolopuqimi.yaml
Config file
```
{
        "serverRoot": "http://localhost:8000",
        "port": 8000,
        "dbtype": "sqlite3",
        "dbconfig": "./data/focalboard.db",
        "postgres_dbconfig": "dbname=focalboard sslmode=disable",
        "test_dbconfig": "file::memory:?cache=shared",
        "useSSL": false,
        "webpath": "./pack",
        "filespath": "./files",
        "telemetry": false,
        "webhook_update": [],
        "secret": "wywWdQ3xA9vmmp3B",
        "session_expire_time": 2592000,
        "session_refresh_time": 18000,
        "localOnly": false,
        "enableLocalMode": true,
        "localModeSocketLocation": "/var/tmp/focalboard_local.socket",
        "authMode": "native",
        "mattermostURL": "",
        "mattermostClientID": "",
        "mattermostClientSecret": ""
}
```
docker-compose.yml. I had changed the version to `0.6.7` as it's the latest version
```
version: "3"
services:
  app:
    build:
      context: ./
      args:
        focalboard_version: 0.6.7
    container_name: focalboard
    ports:
      - 30008:8000
    environment:
      - VIRTUAL_HOST=focalboard.local
      - VIRTUAL_PORT=8000
    volumes:
      - "./config-sqlite.json:/opt/focalboard/config.json"
      - "./sqlite:/opt/focalboard/data"
      - "./files:/opt/focalboard/files"
```
